apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcm
namePrefix: mcm-

labels:
  - pairs:
      app.kubernetes.io/name: mcm
      app.kubernetes.io/part-of: mcm
      app.kubernetes.io/component: migrate
      app.kubernetes.io/managed-by: kustomize

resources:
  - mcm-migrate-job.yaml

# Jobs should keep deterministic names when reapplied
generatorOptions:
  disableNameSuffixHash: true
