apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-sql
data:
  00-create-dbs.sql: |
      CREATE ROLE mcm_app LOGIN PASSWORD 'CHANGE_ME';
      CREATE DATABASE mcm OWNER mcm_app;

      CREATE ROLE keycloak LOGIN PASSWORD 'CHANGE_ME';
      CREATE DATABASE keycloak OWNER keycloak;
