apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels: { app.kubernetes.io/name: api }
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: api
          image: ghcr.io/yourorg/mcm:latest # overridden in overlays
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mcm-db-secret
                  key: DATABASE_URL
            - name: KEYCLOAK_URL
              value: "http://mcm-keycloak.mcm.svc.cluster.local:8080"
          readinessProbe:
            httpGet: { path: /healthz, port: http }
          livenessProbe:
            httpGet: { path: /livez, port: http }
