apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/yourorg/mcm
    newTag: ${GIT_SHA}
  - name: quay.io/keycloak/keycloak
    newTag: 24.0.5

patches:
  - path: patches/mcm-deployment.yaml
  - path: patches/ingress-host.yaml
  - path: patches/storage-and-resources.yaml
